### ISSUE TITLE
production build failed for new CI

### ISSUE THREAD

**Issue by 634750802** [pingcap-inc/tidb.io#371]
See c0406a1 for production build log

Sentry's env was not passed while building, please add: 
- `SENTRY_TOKEN` (already configured)
- `SENTRY_RELEASE`(should be dynamically generated)

to build phase.

**Comment by 634750802** [comment]
not fixed by #374

**Comment by xiyan128** [comment]
Fix attempted in #376. Not quite sure about the production ci behavior though. @634750802

**Comment by 634750802** [comment]
Not work https://github.com/pingcap-inc/tidb.io/runs/5354241879?check_suite_focus=true

**Comment by cw1997** [comment]
It works now after I set the config 'ignoreEmpty' to true, refer to this commit: https://github.com/pingcap-inc/tidb.io/commit/8bd86a982a777566004af4815353413d35044f8b
